spring.application.name=dataweave

spring.datasource.url=jdbc:postgresql://localhost:5432/dataweave
spring.datasource.username=dataweave
spring.datasource.password=dataweave

spring.jpa.hibernate.ddl-auto=none

spring.datasource.hikari.maximum-pool-size=10